"""empty message

Revision ID: 09a01e622e71
Revises: a183f72f2d44
Create Date: 2020-08-15 08:50:04.773230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a01e622e71'
down_revision = 'a183f72f2d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AssignedChore', sa.Column('duration', sa.String(length=120), nullable=True))
    op.add_column('AssignedChore', sa.Column('frequency', sa.String(length=120), nullable=True))
    op.drop_column('AssignedChore', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AssignedChore', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('AssignedChore', 'frequency')
    op.drop_column('AssignedChore', 'duration')
    # ### end Alembic commands ###
