"""empty message

Revision ID: 46dd6148b0ac
Revises: bab44610235f
Create Date: 2020-08-10 18:06:09.791365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dd6148b0ac'
down_revision = 'bab44610235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Chore', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chore', type_='unique')
    # ### end Alembic commands ###
