"""empty message

Revision ID: a183f72f2d44
Revises: 46dd6148b0ac
Create Date: 2020-08-14 08:34:42.656467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a183f72f2d44'
down_revision = '46dd6148b0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Chore_description_key', 'Chore', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Chore_description_key', 'Chore', ['description'])
    # ### end Alembic commands ###
