"""empty message

Revision ID: bab44610235f
Revises: 
Create Date: 2020-08-09 16:54:20.151566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab44610235f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Area', ['name'])
    op.create_unique_constraint(None, 'Worker', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Worker', type_='unique')
    op.drop_constraint(None, 'Area', type_='unique')
    # ### end Alembic commands ###
