"""empty message

Revision ID: e519f20d0fa0
Revises: 09a01e622e71
Create Date: 2020-08-15 12:13:43.769591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e519f20d0fa0'
down_revision = '09a01e622e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AssignedChore', 'duration',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('AssignedChore', 'frequency',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AssignedChore', 'frequency',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('AssignedChore', 'duration',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
